### ISSUE TITLE
Include example text files on the ImageJ plugin page

### ISSUE THREAD

**Issue by saviola777** [thorstenwagner/ij-particlesizer#2]
Hello,

among the examples on the [ImageJ plugin page](http://imagej.net/ParticleSizer) there are only images included, not the generated text files. We want to reference the ParticleSizer in the NanoDefiner e-tool because the user can directly upload text files generated by the ParticleSizer. It would be nice if the user could see an example of such a file without having to install and use the ParticleSizer (e.g. if they want to transform whatever file format they have to a format compatible with the ParticleSizer output).

**Comment by thorstenwagner** [comment]
is there already a NanoDefiner e-tool webpage? I can add an entry that there is an export function for the nanodefiner-etool and how to use it. Would that be enough?

**Comment by saviola777** [comment]
Yeah, that would be fine. We don't have a webpage yet (just a [public test installation](https://labs.inf.fh-dortmund.de/NanoDefiner/)), but we plan to bring it to GitHub/GitLab later this year. I'll give you an update here when that happens.

**Comment by thorstenwagner** [comment]
Sorry that it tooks me so long. I will add the information tomorrow!

**Comment by thorstenwagner** [comment]
@saviola777 Done! Please see
https://imagej.net/ParticleSizer#Use_the_ParticleSizer_with_the_NanoDefiner_e-tool

**Comment by saviola777** [comment]
Thanks!
